### ISSUE TITLE
Pre-Commit hook is not set up to consider Windows devices.

### ISSUE THREAD

**Issue by AceHunterr** [wagtail/wagtail#10172]
### Issue Summary
1. While setting up the Pre-Commit hook for windows the following error is encountered:

### ``` ModuleNotFoundError: No module named 'resource' ```
<br>

After a bit of stack overflowing the solution is obtained as 

``` 'resource' is a Unix-specific package ``` which does not work for windows and hence the pre-commit is unable to be set-up for windows.

#### Link for Reference:  [No Module named 'resource'](https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource)
<br>

2. Another issue that is related to pre-commit is that it doesn't auto-detect the node the version:

` default_language_version:  node: system `

but instead have to change the ```node:system``` to ```node:default``` manually in the '.pre-commit-config.yaml' file.
<br>
The pre-commit auto update reverts it back to `node: system` which raises the error `return code: 1 stdout: (none) stderr: installing system node.js is not supported!`

### Steps to Reproduce
1. Use the Windows operating system.
2. Run `pre-commit install` to install the pre-commit hook.
3. Then try committing changes to the repository.

**Comment by lb-** [comment]
See additional comments about this issue

* https://github.com/wagtail/wagtail/issues/10129#issuecomment-1445397701
* https://github.com/wagtail/wagtail/issues/10129#issuecomment-1445469477
* https://github.com/wagtail/wagtail/issues/10129#issuecomment-1445476212

**Comment by lb-** [comment]
@Lovelyfin00  any chance you can see if you can confirm this bug on Windows?

**Comment by Lovelyfin00** [comment]
I'll test it out now

**Comment by Lovelyfin00** [comment]
I just tried it and it worked....
Did I miss a step?
I installed the pre-commit package manager
Then made changes in some files
Ran `git add` and `git commit -m "heelo"` and it worked

![image](https://user-images.githubusercontent.com/38161296/222141012-26d3e914-11b9-454e-93e7-5a4a21b2321e.png)

**Comment by Lovelyfin00** [comment]
I downgraded the virtualenv version to `20.0.33` and pre-commit to `2.10.1` and I got almost same error

```
[INFO] Installing environment for https://github.com/timothycrosley/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Hp\\Desktop\\Wagtail Codebase\\env\\Scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\Hp\\.cache\\pre-commit\\repo5t42i7j6\\py_env-python3')
return code: 1
expected return code: 0
stdout:
    KeyError: 'scripts'

stderr:
    C:\Users\Hp\Desktop\Wagtail Codebase\env\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: 
setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(

Check the log at C:\Users\Hp\.cache\pre-commit\pre-commit.log

``

**Comment by lb-** [comment]
Ok thanks @Lovelyfin00 - looks like there could be a few issues here on Windows. I'll flag this as confirmed.

**Comment by rickturner2001** [comment]
Hey, @Lovelyfin00  I've been trying to reproduce the same error on my windows machine but I couldn't get it to work. Can you please tell me more about how you set up your dev environment?

**Comment by rickturner2001** [comment]
@Lovelyfin00 

The problem is that Semgrep **does not** have native support for Windows platforms. 

We can easily get around the node installation issue by enforcing a node version, instead of ```system```, like so:

```yaml
default_language_version:
  node: 14.17.6
``` 

This will run all the tests and formatting tools, however, it will fail once it reaches Semgrep:

```bash
black................................................(no files to check)Skipped
isort................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
prettier.................................................................Passed
eslint...............................................(no files to check)Skipped
stylelint............................................(no files to check)Skipped
curlylint............................................(no files to check)Skipped
DjHTML...............................................(no files to check)Skipped
semgrep..................................................................Failed
- hook id: semgrep
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Scripts\semgrep.EXE\__main__.py", line 4, in <module>
  File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\__main__.py", line 4, in <module>
    from semgrep.cli import cli
  File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\cli.py", line 8, in <module>
    from semgrep.commands.ci import ci
  File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\commands\ci.py", line 16, in <module>
    import semgrep.semgrep_main
  File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\semgrep_main.py", line 25, in <module>
    from semgrep.core_runner import CoreRunner
  File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\core_runner.py", line 6, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

Semgrep's[ official documentation](https://semgrep.dev/docs/getting-started/) offers installation methods for Linux, macOS, and Docker, but not Windows; in fact, they even encourage developers to use WSL on windows platforms.

I don't think it would be appropriate to create a ```Dockerfile``` to host the python installation.

 Please consider installing WSL and configuring a [dev environment](https://docs.wagtail.org/en/stable/contributing/developing.html) there.

**Comment by Lovelyfin00** [comment]
> @Lovelyfin00
> 
> The problem is that Semgrep **does not** have native support for Windows platforms.
> 
> We can easily get around the node installation issue by enforcing a node version, instead of `system`, like so:
> 
> ```yaml
> default_language_version:
>   node: 14.17.6
> ```
> 
> This will run all the tests and formatting tools, however, it will fail once it reaches Semgrep:
> 
> ```shell
> black................................................(no files to check)Skipped
> isort................................................(no files to check)Skipped
> flake8...............................................(no files to check)Skipped
> prettier.................................................................Passed
> eslint...............................................(no files to check)Skipped
> stylelint............................................(no files to check)Skipped
> curlylint............................................(no files to check)Skipped
> DjHTML...............................................(no files to check)Skipped
> semgrep..................................................................Failed
> - hook id: semgrep
> - exit code: 1
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Scripts\semgrep.EXE\__main__.py", line 4, in <module>
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\__main__.py", line 4, in <module>
>     from semgrep.cli import cli
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\cli.py", line 8, in <module>
>     from semgrep.commands.ci import ci
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\commands\ci.py", line 16, in <module>
>     import semgrep.semgrep_main
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\semgrep_main.py", line 25, in <module>
>     from semgrep.core_runner import CoreRunner
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\core_runner.py", line 6, in <module>
>     import resource
> ModuleNotFoundError: No module named 'resource'
> ```
> 
> Semgrep's[ official documentation](https://semgrep.dev/docs/getting-started/) offers installation methods for Linux, macOS, and Docker, but not Windows; in fact, they even encourage developers to use WSL on windows platforms.
> 
> I don't think it would be appropriate to create a `Dockerfile` to host the python installation.
> 
> Please consider installing WSL and configuring a [dev environment](https://docs.wagtail.org/en/stable/contributing/developing.html) there.

Oh wow!
That should solve the original issue
Mine doesn't even run up to that point

**Comment by Lovelyfin00** [comment]
> Hey, @Lovelyfin00 I've been trying to reproduce the same error on my windows machine but I couldn't get it to work. Can you please tell me more about how you set up your dev environment?

I installed pre-commit and then tried committing some changes.

**Comment by AceHunterr** [comment]
> @Lovelyfin00
> 
> The problem is that Semgrep **does not** have native support for Windows platforms.
> 
> We can easily get around the node installation issue by enforcing a node version, instead of `system`, like so:
> 
> ```yaml
> default_language_version:
>   node: 14.17.6
> ```
> 
> This will run all the tests and formatting tools, however, it will fail once it reaches Semgrep:
> 
> ```shell
> black................................................(no files to check)Skipped
> isort................................................(no files to check)Skipped
> flake8...............................................(no files to check)Skipped
> prettier.................................................................Passed
> eslint...............................................(no files to check)Skipped
> stylelint............................................(no files to check)Skipped
> curlylint............................................(no files to check)Skipped
> DjHTML...............................................(no files to check)Skipped
> semgrep..................................................................Failed
> - hook id: semgrep
> - exit code: 1
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Scripts\semgrep.EXE\__main__.py", line 4, in <module>
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\__main__.py", line 4, in <module>
>     from semgrep.cli import cli
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\cli.py", line 8, in <module>
>     from semgrep.commands.ci import ci
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\commands\ci.py", line 16, in <module>
>     import semgrep.semgrep_main
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\semgrep_main.py", line 25, in <module>
>     from semgrep.core_runner import CoreRunner
>   File "C:\Users\rickturner\.cache\pre-commit\repo2q6g1zx7\py_env-python3\Lib\site-packages\semgrep\core_runner.py", line 6, in <module>
>     import resource
> ModuleNotFoundError: No module named 'resource'
> ```
> 
> Semgrep's[ official documentation](https://semgrep.dev/docs/getting-started/) offers installation methods for Linux, macOS, and Docker, but not Windows; in fact, they even encourage developers to use WSL on windows platforms.
> 
> I don't think it would be appropriate to create a `Dockerfile` to host the python installation.
> 
> Please consider installing WSL and configuring a [dev environment](https://docs.wagtail.org/en/stable/contributing/developing.html) there.

Is working with WSL the only way to work around this pre-commit error as I'm still having this kind of issue of pre-commit and I'm unable to push my code due to this...
