### ISSUE TITLE
Table block content is not editable after it has been saved

### ISSUE THREAD

**Issue by nathanielwarner** [wagtail/wagtail#10335]
### Issue Summary

Starting in Wagtail 4.1.4, the table block (`wagtail.contrib.table_block.blocks.TableBlock`) no longer allows you to edit the content after the page has been saved.

### Steps to Reproduce

1. In a Wagtail project, create a `Page` with a `StreamField` that contains `TableBlock` in its `block_types`.
2. In the Wagtail admin, create an instance of this page and save it.
3. Add a table to your stream field, editing it as you like. This works fine.
4. Save the page.
5. Try to edit the table again.
6. Cry.

The expected behavior is that as in Wagtail 4.1.3, the table is able to be edited after it has been saved.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: Python 3.10.10
-   Django version: 3.2.18
-   Wagtail version: 4.1.4
-   Browser version: Firefox 112. Also seen in Chrome 112.

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by ethanaward** [comment]
I'm having this issue as well, it's briefly editable but then becomes completely nonfunctional.

**Comment by lb-** [comment]
I might give this a go if I get the chance tomorrow morning my time.

**Comment by lb-** [comment]
@zerolab I have no idea sorry, after an hour of digging I am more confused than before. Even reverting the change (the part about when `hot.render` is called makes no difference.

Super odd - adding the `afterSelection` callback will not fire once saved and re-loaded, but it will on a new table. It's like it is in readonly mode once data is pulled from the JSON unpacking.

```js
  const defaultOptions = {
    afterSelection: () => {
      console.log('cell selected!');
    },
```

Might need someone with a bit more Handsontable experience on this case.

Relevant docs for reference - https://handsontable.com/docs/6.2.0/Core.html

**Comment by gasman** [comment]
Fixed in #10367

**Comment by nathanielwarner** [comment]
I've updated to [Wagtail 4.1.5](https://docs.wagtail.org/en/stable/releases/4.1.5.html), but the issue is still present... Still stuck on 4.1.3 for now.
