### ISSUE TITLE
Wrong z-index of date/time/datetime pickers

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3604]
Can be reproduced on Wagtail 1.10 using Chrome 58.0.3029.110 (64-bit).

Can be fixed by setting `z-index >= 100`, but I'm not sure where it should be fixed it because pickers are from 3rd party jQuery library .

![screen shot 2017-05-19 at 16 10 21](https://cloud.githubusercontent.com/assets/509198/26254243/c93439c8-3cad-11e7-930a-9699f892df7b.png)

**Comment by thibaudcolas** [comment]
Removing `easy` label – it's never easy to change the z-index in a big project without future repercussions.

**Comment by strindhaug** [comment]
Is it really desirable to have the date picker float above the save/preview bar?

I think it would be sufficient to just make sure you can scroll down and see the whole date-picker. If we just increase the minimum height by upping the margin-bottom of the `.page-editor .content-wrapper` from 10em to at least 17em or perhaps 20em to be sure (when I tested with dev-tools 17em seems to be the minimum needed), it should always be possible to scroll down and see the whole picker.


wagtail/wagtailadmin/static_src/wagtailadmin/scss/layouts/page-editor.scss:
```sass
.page-editor {
    .content-wrapper {
        margin-bottom: 20em;  // extra space for the date picker 
    }
    // ...
}
```
20em at 12.8px font-size is 256px and the date picker is about 230px tall. With the additional padding inside the form this should enough to always see the whole picker.

**Comment by gasman** [comment]
This also prevents date pickers from appearing on date fields inside modals, since the `modal-backdrop`, `modal` and `modal-dialog` elements have z-indexes in the range 490-510, putting them in front of the date picker.

**Comment by thibaudcolas** [comment]
This will likely be fixed by #8901.

**Comment by lb-** [comment]
If anyone can confirm this is still an issue in 4.1 LTS - would be good to check.

**Comment by gasman** [comment]
This does still exist in current main:

![Screenshot 2022-11-22 at 12 33 05](https://user-images.githubusercontent.com/85097/203315483-65e12d7b-d636-457e-bdf6-cf64b4c2006f.png)

It appears that it was fixed for date pickers in modals as part of #8901, though.

**Comment by lb-** [comment]
Still broken in modals, but here is a PR up with a fix https://github.com/wagtail/wagtail/pull/10266
