### ISSUE TITLE
`WAGTAILAPI_LIMIT_MAX = None` not working

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3766]
According to the note at http://docs.wagtail.io/en/v1.11.1/advanced_topics/api/v2/usage.html#pagination, it should be possible to set `WAGTAILAPI_LIMIT_MAX = None` to disable the upper bound on the `?limit` parameter on API responses. However, according to https://stackoverflow.com/questions/45680293/wagtail-cms-apiv2-pagination-not-showing-numbers-or-next-previous?noredirect=1#comment78319332_45680293 this fails with the error: `TypeError at /api/v2/pages/ unorderable types: NoneType() < int()`.

Need to confirm that this is indeed the case, and apply a fix (with test coverage).

**Comment by gasman** [comment]
There are also a few other places in the docs that mention `WAGTAILAPI_LIMIT_MAX`, but don't mention the fact that it's possible to set it to `None`: http://docs.wagtail.io/en/v1.11.1/search.html?q=WAGTAILAPI_LIMIT_MAX&check_keywords=yes&area=default. Once this is fixed, it would be a good idea to update the docs so that this is mentioned in all relevant places.

**Comment by jcronyn** [comment]
Working on this now.

**Comment by gasman** [comment]
Fixed in #3770

**Comment by vladox** [comment]
seems to be some kind of regression bug because in 2.3 this is still not working WAGTAILAPI_LIMIT_MAX gets always overridden to 20 no matter the value set to WAGTAILAPI_LIMIT_MAX

**Comment by gasman** [comment]
@vladox It's working for me when testing against [bakerydemo](https://github.com/wagtail/bakerydemo). `http://localhost:8000/api/v2/pages/?limit=25` initially returns

```
{
    "message": "limit cannot be higher than 20"
}
```

but when I add `WAGTAILAPI_LIMIT_MAX = 30` to settings, I get a page of 25 results as expected.

**Comment by vladox** [comment]
@gasman you are right I misunderstood how this works, sorry for the confusion
