### ISSUE TITLE
Wrong SQL syntax generated on multiword MySQL search queries

### ISSUE THREAD

**Issue by ACMCMC** [wagtail/wagtail#7727]
### Issue Summary

When doing a three-word (or more) search query, such as:

```python3
search("W1 W2 W3", myModel, operator='and')
```

It errors with `django.db.utils.ProgrammingError: (1064, "syntax error, unexpected '+'")`.

This is caused by the query getting translated to `'++W1 +W2 +W3'`.

This issue appears when #7725 is solved. Found by the report of @cnk on #7719.

### Steps to Reproduce

1. In the wagtail.search.tests.test_backends.BackendTests.test_search_and_operator method, change the search query to "JavaScript Definitive Guide" instead of "JavaScript Definitive".
2. Run the test on a MySQL database environment.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no (I will try to test it if PR #7726 passes).

### Technical details

* Python version: 3.9.1
* Django version: 3.1.13
* Wagtail version: 2.16a0

### Solution ideas

A possible way to solve the issue would be to instead translate the query to `'+(+W1 +W2) +W3'`.

**Comment by ACMCMC** [comment]
I will submit a PR with the solution soon 🥰

**Comment by gasman** [comment]
Fixed in #7726

**Comment by berycz** [comment]
this is not really fixed tho, check https://github.com/wagtail/wagtail/discussions/8094
(not sure if I should post a new issue?)

**Comment by ACMCMC** [comment]
> this is not really fixed tho, check https://github.com/wagtail/wagtail/discussions/8094
> (not sure if I should post a new issue?)

I believe it should be a new issue, because the root of the problem seems to be a different one :)
