### ISSUE TITLE
Refine hover / focus styles for title field’s comment button

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9202]
As of Wagtail 4, our title field now has a border that only reveals on hover. It also has a "Add comment" button revealed on hover. Both elements are currently out of sync – if the user hovers / focuses the comment button, the border doesn’t show:

![Title field hover / focus recording](https://user-images.githubusercontent.com/877585/190166644-05447e50-1d17-4f04-8d72-d6cf365901d6.gif)

It would be nice if those were always in sync, similarly to what #9164 did for the choosers.

Looking at the styles,

https://github.com/wagtail/wagtail/blob/66ea563fece0133c71a62b23af27fd22f8a8fe98/client/scss/components/forms/_title.scss#L35-L37

I believe this would need to change to applying the styles based on hover / focus within the parent element. Something like (untested):

```scss
// Styles for the title field when at the top of the page.
// It’s the first panel when comments are disabled, second if enabled.
.w-panel.title:nth-child(1),
.w-panel.title:nth-child(2) {
  .w-panel__header {
    @apply w-sr-only;

    .w-panel__anchor,
    .w-panel__toggle {
      @apply w-hidden;
    }
  }

  input,
  textarea,
  .Draftail-Editor .public-DraftEditor-content {
    @apply w-h1;
    color: $color-input-text;
    // Slightly out-dented so the field’s is horizontally aligned.
    padding-inline-start: theme('spacing[1.5]');
    margin-inline-start: calc(-1 * theme('spacing[1.5]'));

    &:not([aria-invalid='true']) {
      border-color: transparent;
    }
  }

    &:not(:hover, :focus-within) :is(input, textarea, .Draftail-Editor .public-DraftEditor-content) {
      border-color: transparent;
    }
}
```

We’d need to make sure this looks correct when hovering/focusing title fields with errors, and tweak if needed.

**Comment by alvinokafor** [comment]
Hi @thibaudcolas, I am an outreachy intern an di would love to take this issue up

**Comment by osujipius** [comment]
Hi.. @alvinokafor I am currently working on this

**Comment by thibaudcolas** [comment]
@OsujiPius in the future make sure to claim a task before someone else does! And @alvinokafor, no need to ask, just say you’re taking it on and let us know how you get on.

**Comment by Buduzz** [comment]
Hi @thibaudcolas, has any PR been created for this issue? If no, I would like to jump on it and get it done as soon as possible

**Comment by lb-** [comment]
Is anyone actively working on this issue?

@alvinokafor  @OsujiPius  or @Buduzz

**Comment by Julietadeboye** [comment]
Hi LB, I'll work on this issue. Thanks

**Comment by lb-** [comment]
Thanks @Julietadeboye - assigned to you for now.

**Comment by Julietadeboye** [comment]
![Screenshot (488)](https://user-images.githubusercontent.com/62646559/205515411-f289c11d-a01d-4c89-8ed1-070c0844bb8a.png)
This issue seems to have been fixed already

**Comment by Srishti-j18** [comment]
I can confirm this issue is still there and hasn’t been resolved yet. Since it’s been a long time with no updates, I’m unassigning it so anyone can take it.

https://github.com/user-attachments/assets/a52df763-41a5-4906-ad10-1d6ee6ec8df4

**Comment by Srishti-j18** [comment]
@thibaudcolas 

I have a little confusion about the desired outcome for this issue.
I mean, should the title border always be visible like other fields:

https://github.com/user-attachments/assets/34d694fd-8912-4b80-a039-dd2e95261772

Or should it appear only (when hovering over the comment button | when the comment button is enabled | when hovering over the input | when the placeholder is shown)?
